출처 : http://pythonkim.tistory.com/8?category=573319

In [17]:
import tensorflow as tf

#### 문자열 상수 저장

In [20]:
def hello():
    a = tf.constant('hello, tensorflow!');
    print(a)

    # 구동하기 위한 (연산을 실행하기 위한) 준비
    sess = tf.Session()
    result = sess.run(a)
    
    print(result)
    print(type(result))
    print(result.decode(encoding='utf-8'))
    print(type(result.decode(encoding='utf-8')))
    
    sess.close()

In [21]:
hello()

Tensor("Const_4:0", shape=(), dtype=string)
b'hello, tensorflow!'
<class 'bytes'>
hello, tensorflow!
<class 'str'>


#### 숫자  상수 저장

In [18]:
def constant():
    a = tf.constant(2)
    b = tf.constant(3)
    
    with tf.Session() as sess:
        result = sess.run(a+b)
        #int32
        print(type(result))
        print(result)
        
        print(result + 7)
        #int64
        print(type(result + 7))

In [19]:
constant()

<class 'numpy.int32'>
5
12
<class 'numpy.int64'>


#### placeholder
뜻 : 자리만 차지하고 있는 물건이나 사람.
tensorflow 에서는 '머신러닝에 전달되는 데이터를 변경하기 위한 수단'으로 통한다.

In [29]:
def placeHolder():
    # 나중에 전달할 데이터를 결정하기 위해서
    a = tf.placeholder(tf.int16)
    b = tf.placeholder(tf.int16)
    
    add = tf.add(a, b)
#    mul = tf.mul(a, b)
    
    with tf.Session() as sess:
        # feed_dict을 사용하여 파라미터 전달
        # dictionary 자료형을 사용하여 파라미터의 갯수에 제한이 없다고 한다.
        r1 = sess.run(add, feed_dict={a: 2, b: 3})
#        r2 = sess.run(mul, feed_dict={a: 2, b: 3})
        
        print(type(r1))
#        print(r1, r2) 
        print(r1)

In [30]:
placeHolder()

<class 'numpy.int16'>
5


In [33]:
def showTensor():
    sess = tf.InteractiveSession()
    
    x = tf.Variable([1.0, 2.0])
    a = tf.constant([3.0, 3.0])
    
    x.initializer.run()
    
#    sub = tf.sub(x, a)
#    print(sub.eval())
    
    print('----------------------')
    
    print(a.eval())
    print(x.eval())
    
    b = tf.random_uniform([3], -1.0, 1.0)
    print(type(b))
    print(b.eval())
    
    w = tf.Variable(tf.random_uniform([5, 3], 0, 32, dtype=tf.int32))
    w.initializer.run()
    print(w.eval())
    
    print('----------------------')
    
    x = ([1., 1.], [10., 2.])
    print(tf.reduce_mean(x).eval())
    print(tf.reduce_mean(x, 0).eval())
    print(tf.reduce_mean(x, 1).eval())
    
    sess.close()

In [34]:
showTensor()

----------------------
[ 3.  3.]
[ 1.  2.]
<class 'tensorflow.python.framework.ops.Tensor'>
[ 0.60773778  0.90442562 -0.6466465 ]
[[31  0 20]
 [ 8 11 16]
 [30 30 22]
 [26  4 30]
 [22 12 26]]
----------------------
3.5
[ 5.5  1.5]
[ 1.  6.]
